### ISSUE TITLE
github action to automatically close the issue after it  PR is merged 

### ISSUE THREAD

**Issue by Ankita297** [Vishal-raj-1/Awesome-JavaScript-Projects#988] opened 2021-04-13 14:21 UTC
## Is your feature request related to a problem? Please describe.
Many issue are still open even if its PR got merged .
## Describe the solution you'd like
I will add github action for that .
## Additional context
Add any other context about the feature request here.

**Comment by Ankita297** [comment] 2021-04-14 02:54
@ridsuteri  @Vishal-raj-1  @urvashi-code1255  Can i work on this ?

**Comment by Ankita297** [comment] 2021-04-15 17:36
@harshgupta20 can i work on this ?

**Comment by ridsuteri** [comment] 2021-04-16 03:53
@Ankita297 github automatically closes the issue after a PR to that issue is merged if the issue is linked to the PR :)

**Comment by ridsuteri** [comment] 2021-04-16 03:55
@Ankita297 i don't think we need a github action for that ...
also if you can please share a demo ?

**Comment by Ankita297** [comment] 2021-04-16 04:01
@ridsuteri  As you can see there are issues whose PR got merged even then issue  are still open  . So I think we can implement a gitub action for that

**Comment by Ankita297** [comment] 2021-04-16 04:03
Also i want to ask one more thing like issues whose corresponding PR has conflicts and it has not been resolved for like many days 
.So  will you assign them to someone else ?

**Comment by ridsuteri** [comment] 2021-04-16 17:13
> @ridsuteri As you can see there are issues whose PR got merged even then issue are still open . So I think we can implement a gitub action for that

ohk so that action will close the existing open issues?

**Comment by ridsuteri** [comment] 2021-04-16 17:16
> Also i want to ask one more thing like issues whose corresponding PR has conflicts and it has not been resolved for like many days
> .So will you assign them to someone else ?

yes @Ankita297 ! participants who are not resolving/responding to the PR after the conflcts till certain days...
those issues will be assigned to someone else

**Comment by Ankita297** [comment] 2021-04-18 03:29
> > @ridsuteri As you can see there are issues whose PR got merged even then issue are still open . So I think we can implement a gitub action for that
> 
> ohk so that action will close the existing open issues?

Yes , Can i try on that ?

**Comment by Ankita297** [comment] 2021-04-18 03:29
@ridsuteri @harshgupta20 @Vishal-raj-1 ?

**Comment by ridsuteri** [comment] 2021-04-18 04:03
@Ankita297 ok go ahead ! but please try to make a descriptive PR for this issue :)

**Comment by harshgupta20** [comment] 2021-05-09 19:17
@Ankita297 Any update? kindly reply within 2 days or else I have to close it.

**Comment by Ankita297** [comment] 2021-05-10 01:52
Sorry Sir i will not able to work on this issue You can close it .

**Closed** 2021-05-10 06:27 UTC
Labels: assigned, gssoc21
